Fixes client credentials grant for KeycloakAdmin
marcospereirampj/python-keycloak pull request #281
Opened 2022-03-17 02:02 UTC by andricDu

# Summary

This is a fix for the following issue that describes an issue with using client credentials with the `KeycloakAdmin` client: https://github.com/marcospereirampj/python-keycloak/issues/269

The `if` conditions are restructured in the `get_token` method such that client_credentials and password grant types are both exclusive and properly executed. Common token and header logic between grant types is encapsulated by the inner function. 

## Validation
Verified with the following script and running latest keycloak via docker:
```
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:17.0.0 start-de
```

### Script
```python
from keycloak import KeycloakAdmin

print("\n****** ADMIN USER ******")
admin = KeycloakAdmin(server_url="http://localhost:8080", username="admin", password="admin")
print(admin.token)

print("\n\n****** SERVICE ACCOUNT ******")
service_account = KeycloakAdmin(server_url="http://localhost:8080", client_id="test", client_secret_key="2pZ8gI2jhSGMHi0RPrRle1qOIteRAsrE")
print(service_account.token)
```

### Output
```
$ python verify.py 

****** ADMIN USER ******
{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJINWg5bUphR251Q2x5QnZnVDZpenMzLXVjai1qc0dYdndTdVhWTTVoLWlBIn0.eyJleHAiOjE2NDc0ODE0NjgsImlhdCI6MTY0NzQ4MTQwOCwianRpIjoiOTlhZmM4NTktOGIxOS00YjI4LTgyMzMtNTJhMDQ2MjYyOTc1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiJjNmQ5Y2E2My1jOWY3LTRkNmItODI1NS04ZjE2N2RjN2M3ZmIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiMDFjODg3YTUtM2E1OC00NzQ3LTkzMmMtOWU3NzM0NWQyNTVkIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjAxYzg4N2E1LTNhNTgtNDc0Ny05MzJjLTllNzczNDVkMjU1ZCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.i7qziOShBMCJQKFPX2-1UFk6dKDacAoftRjdkEpxT7PO5IR_s3Zj7aRwX_TnrT3VXFvT5xXDJS8mVI4GySExyslOo8IIawNWFwIcuDkM2kiySYC-crWsVG4wlk40wt2Q5A436mpzm-hV5wsl1dr4vEvk2SvAYzKkB71WxrDhQ9JCPwG-oSyGkxxRFIHXFptLj1Efa76gYgt_7FGgzeJLiTyndNj7XagYqz4Ug-qj6fJM1igdeSAdjgEM1yWGRFsv2DI1-SlSmZFx9RXc55en8aKqsri5w5lPsxTJqWki4qfyChE80A_XBD-GPYTbPQsP8biOcE3SM9perYs5Zmjw7g', 'expires_in': 60, 'refresh_expires_in': 1800, 'refresh_token': 'eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1OTlhMzgxZC0xZWVhLTRmMTgtODU2Yi1lMWJhNTRhNTNjMzEifQ.eyJleHAiOjE2NDc0ODMyMDgsImlhdCI6MTY0NzQ4MTQwOCwianRpIjoiM2FlNzU5YjAtOGRjNi00ZWE4LWJlYzQtYWY1MDNjZmQ4OGQ5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInN1YiI6ImM2ZDljYTYzLWM5ZjctNGQ2Yi04MjU1LThmMTY3ZGM3YzdmYiIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiMDFjODg3YTUtM2E1OC00NzQ3LTkzMmMtOWU3NzM0NWQyNTVkIiwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiMDFjODg3YTUtM2E1OC00NzQ3LTkzMmMtOWU3NzM0NWQyNTVkIn0.Eh9CJ3npM2ZatQb7EtzSEog6gTwYv2mw0PaO44KGMao', 'token_type': 'Bearer', 'not-before-policy': 0, 'session_state': '01c887a5-3a58-4747-932c-9e77345d255d', 'scope': 'profile email'}

****** SERVICE ACCOUNT ******
{'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJINWg5bUphR251Q2x5QnZnVDZpenMzLXVjai1qc0dYdndTdVhWTTVoLWlBIn0.eyJleHAiOjE2NDc0ODE0NjgsImlhdCI6MTY0NzQ4MTQwOCwianRpIjoiODhmMThjMjAtMzdhYS00YThlLTkyOWUtMGZkZTA1ZWQ3NTRmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYTU5ODlkYmQtYmNiMy00YzNjLTk4MDEtZWRkNDc1YTJkZTE1IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGVzdCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1tYXN0ZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiY2xpZW50SG9zdCI6IjE3Mi4xNy4wLjEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImNsaWVudElkIjoidGVzdCIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC10ZXN0IiwiY2xpZW50QWRkcmVzcyI6IjE3Mi4xNy4wLjEifQ.k7H7KX7-ZjOU1fhz3gzXni-ENa-YXfiyt4JXIHJ8Z21iicMNqF9nAfbV2YWdm1HhYnoGw9mZ8-FlNoaaiuASR3_UJ9T76UHmYOQU_fLxxx3k1vBbX93lW5_PyzjOPwGyGylE1Fbp50pBCE2dafU92SDuOxbxNRPuTYFLQKShPJ4FL2elHFHQ1E0l259A2Hc3VSgvwm2DBj9L9PJFddeW2asbBe3xME5XHsugIdiIMO8h5HZfTNfnNLo614_fFE05r7_37k8DqnHTk2btgGw30YIBawbryXIW_fQJXiSzfY-XVbvVYF-trbFX5A_SYt5sBV5khq3wXV2paB6lffv5Fg', 'expires_in': 60, 'refresh_expires_in': 0, 'token_type': 'Bearer', 'not-before-policy': 0, 'scope': 'profile email'}
```

2022-03-17 13:24 UTC, andricDu commented
@marcospereirampj let me know if there is anything I can do to get this merge expedited.

2022-05-02 06:18 UTC, TomasChmelik commented
Any news on this?

2022-05-03 11:04 UTC, dominikschopf commented
@marcospereirampj ping. This issue prevents a lot of people from using the new version.

2022-05-20 05:02 UTC, ryshoooo requested changes
Minor few changes, otherwise looks good! thanks a lot :) Remember to update your branch with the latest master.

2022-05-20 05:02 UTC, ryshoooo commented on keycloak/keycloak_admin.py
> +        def set_token_get_header(identifier, secret, grant):
Might I suggest to make this into a method instead of a function defined inside of a method? I.e. something like `def _set_token_get_header(self, identifier, secret, grant)`. Adding some docstrings to it as well for documentation purposes.

2022-05-20 05:02 UTC, ryshoooo commented on keycloak/keycloak_admin.py
> +            self._token = self.keycloak_openid.token(identifier, secret, grant_type=grant)
I'd suggest `self.token = ...` instead of `self._token` in order to call the setter method.

2022-05-24 21:14 UTC, ryshoooo commented
Will close this as #324 was merged.

2022-05-24 21:14 UTC, closed without merging